### ISSUE TITLE
server crasher i no have sure why

### ISSUE THREAD

**Issue by joaoespanhol** [magmamaintained/Magma-1.18.2#10]
**Minecraft Version:** 1.18.2

**Forge Version:** last version

**Logs:**[ {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://mclo.gs/v5XzJhx](https://mclo.gs/v5XzJhx)
**Steps to Reproduce:**
1. start
2. i no have sure

**Description of issue:**
server crasher.

**Comment by joaoespanhol** [comment]
I NO HAVE THIS CRASHER OTHER VERSION
I went back to the version: magma-1.18.2-40.2.14-a07c744-server.jar

**Comment by Ashley123477** [comment]
I am also having this issue

**Comment by joaoespanhol** [comment]
s2
