### ISSUE TITLE
mod error

### ISSUE THREAD

**Issue by joaoespanhol** [magmamaintained/Magma-1.18.2#11]
**Minecraft Version:** 1.18.2

**Forge Version:** 1.18.2:40-2-14

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. put mod: AutoRestart-1.18.2-2.0.0.jar
 2. waiting mod restart
 3. you go see erro console

**Description of issue:**
https://mclo.gs/WXmh56P

**Comment by TonimatasDEV** [comment]
I can't reproduce the error.
