### ISSUE TITLE
bug Mod: Multiworld-Forge-1.4.1.jar

### ISSUE THREAD

**Issue by joaoespanhol** [magmamaintained/Magma-1.18.2#12]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.14

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. put mod
 2. start server
 3.  ./mw create hsmp NORMAL
 4.  ./mw tp hsmp

**Description of issue:**

no show new world D:
![Uploading image.png…]()

**Comment by TonimatasDEV** [comment]
Uploading image

![image](https://github.com/magmamaintained/Magma-1.18.2/assets/79017964/4fc9c349-fb83-4989-a645-118e9461164d)

**Comment by joaoespanhol** [comment]
> Uploading image
> 
> ![image](https://private-user-images.githubusercontent.com/79017964/298408052-4fc9c349-fb83-4989-a645-118e9461164d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4NzQ1ODgsIm5iZiI6MTcwNTg3NDI4OCwicGF0aCI6Ii83OTAxNzk2NC8yOTg0MDgwNTItNGZjOWMzNDktZmI4My00OTg5LWE2NDUtMTE4ZTk0NjExNjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDIxNTgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjU5ZjllNGUxMTlhOTkxYWI2MDFkNjRjNjRmYWM5ZDhiZTYzMjY0YWY4YjE1YjVkZmU2YjRkNzZiOTI5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CR6fJsanHtF8Yik2h6c7ayFQwWiw8uoB8k3kbWhCk7c)

![image](https://github.com/magmamaintained/Magma-1.18.2/assets/22871432/b2c604b3-9413-46ef-b7b3-6cd4d17fb786)

**Comment by joaoespanhol** [comment]
resigned, solve the world's problem

**Comment by joaoespanhol** [comment]
resigned, solve the world's problem
