### ISSUE TITLE
Atm7 -To The Sky no es compatible

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#13]
Copyright (c) 2024 MagmaFoundation.
--------------------------------------
Running on Java 18.0.2.1 (Azul Systems, Inc.)
Magma version   1.18.2-d1d5c5f
Bukkit version  v1_18_R2
Forge version   40.2.14
--------------------------------------
**Logs:**
[latest (1).log](https://github.com/magmamaintained/Magma-1.18.2/files/14014200/latest.1.log)

**Steps to Reproduce:**
 1. start button
 2. no start

**Description of issue:**

**Comment by TonimatasDEV** [comment]
I cannot reproduce the error. I need more information

**Comment by SrNadien** [comment]
@TonimatasDEV al instalar el modpack borras los mods de cliente y inicias y el servidor crashea al crear el mundo

**Comment by TonimatasDEV** [comment]
@SrNadien Por algo existe el ServerPack, para crear el servidor tienes que descargar el ServerPack

**Comment by SrNadien** [comment]
> @SrNadien Por algo existe el ServerPack, para crear el servidor tienes que descargar el ServerPack

ese ise y daba igualmente errores
