### ISSUE TITLE
redstone arsenal crash

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#15]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.17

**Logs:** 
[crash-2024-02-07_20.40.26-fml.txt](https://github.com/magmamaintained/Magma-1.18.2/files/14203945/crash-2024-02-07_20.40.26-fml.txt)

**Steps to Reproduce:**
 1. instal  redstone arsenal
 2. use mod items
 3. crash server

**Description of issue:**

**Comment by TonimatasDEV** [comment]
> **Minecraft Version:** 1.18.2
> 
> **Forge Version:** 40.2.17
> 
> **Logs:** [crash-2024-02-07_20.40.26-fml.txt](https://github.com/magmamaintained/Magma-1.18.2/files/14203945/crash-2024-02-07_20.40.26-fml.txt)
> 
> **Steps to Reproduce:**
> 
> 1. instal  redstone arsenal
> 2. use mod items
> 3. crash server
> 
> **Description of issue:**

Impossible to reproduce
