### ISSUE TITLE
ExcellentCrates Invalid User Data

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#17]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.17

**Logs:** 

![image](https://github.com/magmamaintained/Magma-1.18.2/assets/76491773/f95d9ab7-d67c-4add-a771-adb8e59dd6fb)

**Steps to Reproduce:**
 1. Install plugin ExcellentCrates-4.4.0.jar and NexEngine core
 2. join server
 3. player not join error (Invalid User Data)

**Description of issue:**

**Comment by SrNadien** [comment]
> @SrNadien Server logs?

Screendhto messege

**Comment by C0D3-M4513R** [comment]
Works fine for me with `1.18.2-5012a7f4`.

**Comment by TonimatasDEV** [comment]
@SrNadien Screenshot is not a log

**Comment by SrNadien** [comment]
> Funciona bien para mí `1.18.2-5012a7f4`(sí, todavía es una construcción de magma, no mantenida por magma).
I have the most recent version and it fails. Magma-1.18.2 a6932ea The strange thing is that the console does not produce errors

**Comment by C0D3-M4513R** [comment]
also works fine for me on a6932ea9

**Comment by SrNadien** [comment]
> also works fine for me on [a6932ea](https://github.com/magmamaintained/Magma-1.18.2/commit/a6932ea96a27c083ef037e7692f6b0589f798498)

player join server error player invalid data

**Comment by TonimatasDEV** [comment]
> > also works fine for me on [a6932ea](https://github.com/magmamaintained/Magma-1.18.2/commit/a6932ea96a27c083ef037e7692f6b0589f798498)
> 
> player join server error player invalid data

Modpack? What you use to reproducce it?

**Comment by SrNadien** [comment]
> > > also works fine for me on [a6932ea](https://github.com/magmamaintained/Magma-1.18.2/commit/a6932ea96a27c083ef037e7692f6b0589f798498)
> > 
> > 
> > player join server error player invalid data
> 
> Modpack? What you use to reproducce it?

https://mega.nz/file/Eu9Hia7S#KSP7WPxaGnwQVPAq-tLGmpzDvme3vI4CcR2suwbOdJQ
