### ISSUE TITLE
renderizado

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#18]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.17

**Steps to Reproduce:**
This error occurs when one user places a block, the other user must change the dimension or log in and out of the server to view it.

Another thing is that if you click in the air block by block this error appears

in one player this error does not happen

**Description of issue:**

**Comment by C0D3-M4513R** [comment]
what error? where is the log?

**Comment by SrNadien** [comment]
> what error? where is the log?

wold player entity error

**Comment by TonimatasDEV** [comment]
> > what error? where is the log?
> 
> wold player entity error

Logs?
