### ISSUE TITLE
worldedit spam bug no working

### ISSUE THREAD

**Issue by joaoespanhol** [magmamaintained/Magma-1.18.2#2]
## Summary

(Summarize the bug encountered concisely)

## Steps to reproduce

put mods and plugins start
try use axe

(How one can reproduce the issue - this is very important)

## What is the current list of mods, and include where to download them?
worledit and worldguard
worldedit-bukkit-7.3.0-beta-02.jar

link modpack: https://github.com/Renwyi/modpack/releases/download/HSMP/HSMP.zip

## What is the current bug behavior?

spam console error

when you try to select an area axe, it doesn't do anything

## What is the expected correct behavior?

the plugin works and gives no error

## All relevant logs. All debug, crash log, and log files.
https://mclo.gs/6J4Mbxr

(Paste any relevant logs - please use code blocks (```) to format console output, logs, and code, as
it's very hard to read otherwise.)

**Comment by joaoespanhol** [comment]
bug all version plugin worldedit

**Comment by TonimatasDEV** [comment]
> ## Summary
> (Summarize the bug encountered concisely)
> 
> ## Steps to reproduce
> put mods and plugins start try use axe
> 
> (How one can reproduce the issue - this is very important)
> 
> ## What is the current list of mods, and include where to download them?
> worledit and worldguard worldedit-bukkit-7.3.0-beta-02.jar
> 
> link modpack: https://github.com/Renwyi/modpack/releases/download/HSMP/HSMP.zip
> 
> ## What is the current bug behavior?
> spam console error
> 
> when you try to select an area axe, it doesn't do anything
> 
> ## What is the expected correct behavior?
> the plugin works and gives no error
> 
> ## All relevant logs. All debug, crash log, and log files.
> https://mclo.gs/6J4Mbxr
> 
> (Paste any relevant logs - please use code blocks (```) to format console output, logs, and code, as it's very hard to read otherwise.)

For me WorldEdit plugin works fine
![image](https://github.com/magmamaintained/Magma-1.18.2/assets/79017964/d7caf33d-bc04-47d1-8a3e-081ef9bbb9f6)
