### ISSUE TITLE
Beyond Hearth Crash 

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#20]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.17

**Logs:** 
[crash-2024-02-17_15.02.08-fml.txt](https://github.com/magmamaintained/Magma-1.18.2/files/14320220/crash-2024-02-17_15.02.08-fml.txt)

**Steps to Reproduce:**
 1. install beyond hearth and addon crash 
 2. start server
 3. crash server

**Description of issue:**

**Comment by SrNadien** [comment]
@TonimatasDEV

**Comment by TonimatasDEV** [comment]
Is not a problem of Magma
