### ISSUE TITLE
jobs renorn console spamming

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#21]
Minecraft Version: 1.18.2

Forge Version: 40.2.17

**Logs:** https://mega.nz/file/0yNX0BhR#A1NJCCqhPjpZBl39dJ2fDVSjDRpoeamfHpiKar2trmk

**Steps to Reproduce:**
 1. install plugin 
 2. start server
 3. use commands and jobs spamming console

**Description of issue:**

**Comment by TonimatasDEV** [comment]
Cannot reproducce
