### ISSUE TITLE
crates plus reloaded console spam

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#22]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.14

**Logs:** [latest (5).log](https://github.com/magmamaintained/Magma-1.18.2/files/14350958/latest.5.log)

plugin:https://www.spigotmc.org/resources/cratesplus-reloaded.95122/

**Steps to Reproduce:**
 1. Install crates lus reloaded
 2. start server
 3. console spamming

**Description of issue:**

**Comment by TonimatasDEV** [comment]
Same of #23
