### ISSUE TITLE
plugin portal not working jobs spamming console

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#23]
Minecraft Version: 1.18.2

Forge Version: 40.2.14

**Logs:** 
[latest (5).log](https://github.com/magmamaintained/Magma-1.18.2/files/14351012/latest.5.log)

Jobs:https://www.spigotmc.org/resources/jobs-reborn.4216/

Plugin Portal:https://www.spigotmc.org/resources/plugin-portal.108700/

**Steps to Reproduce:**
 1. install plugin porltal 
 2. start server
 3. plugin not work

**Steps to Reproduce:**
 1. install Jobs v5.2.2.3
 2. start server
 3. console spamming

**Description of issue:**

**Comment by SrNadien** [comment]
plugin portal antes si me funcionaba

**Comment by TonimatasDEV** [comment]
> plugin portal antes si me funcionaba

Antes de que?

**Comment by SrNadien** [comment]
> > plugin portal antes si me funcionaba
> 
> Antes en la penúltima versión de magma y en la dev se reprodujo que no lo carga

**Comment by TonimatasDEV** [comment]
Cannot reproducce
