### ISSUE TITLE
My server crashes without giving any kind of log

### ISSUE THREAD

**Issue by tingamer1234** [magmamaintained/Magma-1.18.2#25]
**Minecraft Version:** {1.18.2}

**Forge Version:** 1.18.2. *40.2.17*

**Logs:** [2024-03-01-9.log](https://github.com/magmamaintained/Magma-1.18.2/files/14466491/2024-03-01-9.log)

**Steps to Reproduce:**
 1. Start the server
 2. Wait a few minutes
 3. The Server crashes without giving any type of log

**Description of issue:** My server is normal, below 10ms, 20 TPS, but out of nowhere the server just crashes without giving any kind of log, and starts again... what could it be?

**Comment by TonimatasDEV** [comment]
Need more info
