### ISSUE TITLE
crash villager entity  org.bukkit.entity.Villager.Profession.ELECTRICIAN

### ISSUE THREAD

**Issue by SrNadien** [magmamaintained/Magma-1.18.2#5]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.2.17

**Logs:** [crash-2023-12-22_19.23.14-server.txt](https://github.com/magmamaintained/Magma-1.18.2/files/13757604/crash-2023-12-22_19.23.14-server.txt)

**Steps to Reproduce:**
 1. start server
 2. Tserch village
 3. crash server

**Comment by TonimatasDEV** [comment]
Fixed in the 1.20.1 repository
