### ISSUE TITLE
server crash (Caught exception during server boot phase, shutting down server)

### ISSUE THREAD

**Issue by joaoespanhol** [magmamaintained/Magma-1.18.2#7]
Mod: weaponleveling
Logs: debug: https://mclo.gs/pCW9VRz 
LastLog: https://mclo.gs/Ng8BpY5 
console: https://mclo.gs/6WOzdFw 

github mod: https://github.com/GeradesoLukas/weaponleveling/issues

**Comment by joaoespanhol** [comment]
https://mclo.gs/x0RA0ec
open again please @TonimatasDEV  server no start

**Comment by TonimatasDEV** [comment]
> https://mclo.gs/x0RA0ec open again please @TonimatasDEV server no start
