### ISSUE TITLE
[Crash] Just download jar and run

### ISSUE THREAD

**Issue by viminio** [magmamaintained/Magma-1.18.2#8]
**Minecraft Version:** 1.18.2

**Forge Version:** 40.2.14

**Logs:** [{Link(s) to GitHub Gist with full latest.log and/or crash report}](https://mclo.gs/IVkAAKb)

**Steps to Reproduce:**
 1. Download this https://github.com/magmamaintained/Magma-1.18.2/releases/download/3098806/magma-1.18.2-40.2.14-3098806-server.jar
 2. Open
 3. Crash

**Description of issue:**
Crash downloading the libraries

**Comment by viminio** [comment]
The error still persists in 4e6857a
https://mclo.gs/xuBBxFh

**Comment by TonimatasDEV** [comment]
> The error still persists in [4e6857a](https://github.com/magmamaintained/Magma-1.18.2/commit/4e6857ab73f7f98094300e236fe0cb40af698b78) https://mclo.gs/xuBBxFh

Wait I'm fixing this

**Comment by TonimatasDEV** [comment]
@viminio Fixed

**Comment by TonimatasDEV** [comment]
> My cache now also includes mohist.

You cache have all maven central
